sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t samu126/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samu126/react-test npm test -- --coverage

after_success:
  - docker build -t samu126/multi-client ./client
  - docker build -t samu126/multi-nginx ./nginx
  - docker build -t samu126/multi-server ./server
  - docker build -t samu126/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push samu126/multi-client
  - docker push samu126/multi-nginx
  - docker push samu126/multi-server
  - docker push samu126/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-635618490012
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY